config/routes.rb
Rails.application.routes.draw do
  root "departments#index"

  resources :departments do 
    resources :items 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, except: [:index, :new, :create]

  def index
    @departments = Department.all
  end

  def show

  end

  def new 
    @department = Department.new 
    render partial: "form"
  end

  def create 
    @department = Department.new(department_params)

    if @department.save
      redirect_to department_path(@department)
    else
      render :new 
    end
  end

  def edit 
    render partial: "form"
  end

  def update
    # Person.update(params[:id]).update(department_params)

    if Department.update(department_params)
      redirect_to department_path(@department)
    else 
      render :edit
    end
  end

  def destroy 
    #Department.find(params[:id]).destroy 
    @department.destroy
    redirect_to departments_path
  end

  private 
  def department_params 
    params.require(:department).permit(:department_name)
  end

  def set_department
    @department = Department.find(params[:id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  
  def index
    @items = @department.items 
  end

  def show
  end

  def view
  end

  def new
    @item = Item.new 
    render partial: "form"
  end

  def create 
    @item = @department.items.new(item_params)

    if @item.save
      redirect_to department_item_path(@department, @item)
    else
      render :new 
    end
  end

  def edit
    render partial: "form"
  end

  def update 
    if @item.update(item_params)
      redirect_to department_item_path(@department)
    else 
      render :edit 
    end
  end

  def destroy
    @item.destroy 
    redirect_to department_items_path(@department)
  end

  private 
  def set_item
    @item = Item.find(params[:id])
  end

  def set_department
    @department = Department.find(params[:department_id])
  end

  def item_params
    params.require(:item).permit(:item_name, :description, :quantity, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<h1><%= @department.id ? 'Edit' : 'Create' %></h1>
<hr />
<%= form_for @department do |f| %>
  <%= f.label :department_name %>
  <%= f.text_field :department_name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/departments/index.html.erb
<h1>Departments</h1>
<%= link_to 'Add a Department', new_department_path %>
<hr />
<h3>Departments</h3>
<ul>
  <% @departments.each do |dep| %>
    <li><%= link_to dep.department_name, department_path(dep) %></li>
  <% end %>
</ul>

app/views/departments/show.html.erb
<h1><%= @department.department_name %></h1>
<hr />
<h2>Available Inventory</h2>
<table>
    <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Description</th>
    </tr>
<% @department.items.each do |item| %>
<tr>
  <td><%= link_to item.item_name, [@department, item] %></td>
  <td><%= link_to item.price, [@department, item] %></td>
  <td><%= link_to item.quantity, [@department, item] %></td>
  <td><%= link_to item.description, [@department, item] %></td>
</tr> 
<% end %>
</table>
<hr />
<button><%= link_to 'Go Back', departments_path %></button>
<button><%= link_to 'Edit Department', edit_department_path(@department) %></button>
<button><%= link_to 'Delete', @department, method: :delete %></button>
<button><%= link_to 'View Inventory', department_items_path(@department) %></button>

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit' : 'Create' %></h1>
<hr />
<%= form_for [@department, @item] do |f| %>
  <%= f.label :item_name %>
  <%= f.text_field :item_name, required: true, autofocus: true %>
  <br />
  <%= f.label :price %>
  <%= f.text_field :price %>
  <br />
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  <br />
  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

app/views/items/index.html.erb
<h1><%= @department.department_name %></h1>
<hr />
<h2>Inventory</h2>
<table>
    <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Description</th>
    </tr>
<% @department.items.each do |item| %>
<tr>
  <td><%= link_to item.item_name, [@department, item] %></td>
  <td><%= link_to item.price, [@department, item] %></td>
  <td><%= link_to item.quantity, [@department, item] %></td>
  <td><%= link_to item.description, [@department, item] %></td>
</tr> 
<% end %>
</table>
<hr />
<button><%= link_to 'Go Back', department_path(@department) %></button>
<button><%= link_to 'Add Inventory Item', new_department_item_path(@department)%></button>

app/views/items/show.html.erb
<h1>Item Details</h1>
<h2><%= @item.item_name %></h2>
<p>Price: <%= @item.price %></p>
<p>Quantity: <%= @item.quantity %></p>
<p>Description: <%= @item.description %></p>
<button><%= link_to 'Add Item', new_department_item_path(@department)%></button>
<button><%= link_to 'Edit Item', edit_department_item_path(@department, @item)%></button>
<button><%= link_to 'Go Back', department_items_path(@department) %></button>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>